server:
  port: 1112

spring:
  application:
    name: eurekaServer
  
eureka:
  instance:
    hostname: peer2
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://peer1:1111/eureka/