server:
  port: 1111

spring:
  application:
    name: eurekaServer
  profiles:
    active: dev
  
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #defaultZone: http://peer1:1111/eureka/
  #server:
    #enableSelfPreservation: false
    #evictionIntervalTimerInms: 4000