server:
  port: 1111

spring:
  application:
    name: eurekaServer
  
eureka:
  instance:
    hostname: peer1
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://peer2:1112/eureka/