server:
  port: 1121
  
spring:
  application:
    name: eureka-provider
    
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
      #defaultZone: http://peer1:1111/eureka/, http://peer2:1112/eureka/