server:
  port: 1122
  
spring:
  application:
    name: eureka-provider
    
eureka:
  instance:
    hostname: localhost
    #leaseRenwlIntervalInSeconds: 10
    #leaseExpirationDurationInSeconds: 30
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
      #defaultZone: http://peer1:1111/eureka/, http://peer2:1112/eureka/